networks:
  itmo:

services:
  backend:
    build:
      context: ./back
    networks:
      - itmo

  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - itmo