networks:
  itmo:

services:
  backend:
    build:
      context: ./back
    networks:
      - itmo

  frontend:
    build:
      context: ./front
    networks:
      - itmo

  nginx:
    image: nginx
    ports:
      - "8000:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    networks:
      - itmo